apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    otus.dz1.service: otus-dz1  # Выбирает Pod с нашими контейнерами
  ports:
    - port: 8000
      targetPort: 8000  # Порт контейнера web-приложения
