apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    otus.dz1.service: otus-dz1  # Выбирает Pod с нашими контейнерами
  ports:
    - port: 5432
      targetPort: 5432  # Порт контейнера db
