kind: Secret
apiVersion: v1
metadata:
  name: cloud-credentials
  namespace: velero
data:
  cloud: >-
    W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gbWluaW9hZG1pbgphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSBtaW5pb2FkbWlu
type: Opaque
